alter session set "_ORACLE_SCRIPT"=true;
CREATE USER vehicledb IDENTIFIED BY root;
GRANT CONNECT TO vehicledb;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO vehicledb;
GRANT UNLIMITED TABLESPACE TO vehicledb;
GRANT CREATE TABLE TO vehicledb;
GRANT CREATE SEQUENCE to vehicledb;
GRANT CREATE TRIGGER TO vehicledb;

  CREATE TABLE "VEHICLEDB"."LOOKUP" 
   (	"TYPE" VARCHAR2(31 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NAME_AR" VARCHAR2(255 CHAR), 
	"NAME_LIC" NUMBER(10,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE TABLE "VEHICLEDB"."VEHICLE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(1,0), 
	"CATEGORY50PER50" NUMBER(1,0), 
	"CDA_INPUT" NUMBER(10,0), 
	"LANGUAGE" VARCHAR2(255 CHAR), 
	"SIJIL_VEHICLE_CODE" NUMBER(10,0), 
	"USED_CATEGORY" NUMBER(1,0), 
	"VEHICLE_MAKER" VARCHAR2(255 CHAR), 
	"VEHICLE_MODEL" VARCHAR2(255 CHAR), 
	"VEHICLE_TYPE_CODE" NUMBER(10,0), 
	"COUNTRY_MAKE_ID" NUMBER(19,0), 
	"NEW_VEHICLE_BODY_TYPE_ID" NUMBER(19,0), 
	"VEHICLE_BODY_TYPE_ID" NUMBER(19,0), 
	"VEHICLE_CATEGORY_ID" NUMBER(19,0), 
	"VEHICLE_TYPE_ID" NUMBER(19,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKR9BRCG2ROY2K65R3VT5OACTFE" FOREIGN KEY ("COUNTRY_MAKE_ID")
	  REFERENCES "VEHICLEDB"."LOOKUP" ("ID") ENABLE, 
	 CONSTRAINT "FKCJ3C76139B85DVWLH70IAV17O" FOREIGN KEY ("NEW_VEHICLE_BODY_TYPE_ID")
	  REFERENCES "VEHICLEDB"."LOOKUP" ("ID") ENABLE, 
	 CONSTRAINT "FK9J5CIAD6WDIVEF7WMCPQT2UX" FOREIGN KEY ("VEHICLE_BODY_TYPE_ID")
	  REFERENCES "VEHICLEDB"."LOOKUP" ("ID") ENABLE, 
	 CONSTRAINT "FK9G9I2PKQMQF7O70HBWEYN7LS2" FOREIGN KEY ("VEHICLE_CATEGORY_ID")
	  REFERENCES "VEHICLEDB"."LOOKUP" ("ID") ENABLE, 
	 CONSTRAINT "FKB7TGOQPO7LC6K7LBDESLB8YA" FOREIGN KEY ("VEHICLE_TYPE_ID")
	  REFERENCES "VEHICLEDB"."LOOKUP" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE SEQUENCE "VEHICLEDB"."VEHICLE_SEQ"
MINVALUE 1
MAXVALUE 9999999999999999999999999999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  
GLOBAL ;

CREATE OR REPLACE TRIGGER "VEHICLEDB"."VEHICLE_AUT_INC"
BEFORE INSERT ON "VEHICLEDB"."VEHICLE"
FOR EACH ROW
BEGIN
  SELECT "VEHICLEDB"."VEHICLE_SEQ".NEXTVAL
  INTO   : new.id
  FROM   dual;
END;

CREATE SEQUENCE  "VEHICLEDB"."LOOKUP_SEQ"  
MINVALUE 1
MAXVALUE 9999999999999999999999999999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  
GLOBAL ;

CREATE OR REPLACE TRIGGER "VEHICLEDB"."LOOKUP_AUT_INC"
BEFORE INSERT ON "VEHICLEDB"."LOOKUP"
FOR EACH ROW
BEGIN
  SELECT "VEHICLEDB"."LOOKUP_SEQ".NEXTVAL
  INTO   : new.id
  FROM   dual;
END;